name: Build and Test

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Check Docker build
        run: |
          docker build -t time-capsule-test .
          
      - name: Run Docker Compose in background
        run: |
          docker compose up -d --build
        env:
          DATABASE_URL: postgresql://timecapsule_user:secure_password_change_this@localhost:5432/time_capsule
          
      - name: Wait for services to be ready
        run: |
          sleep 30
          
      - name: Check service status
        run: |
          docker compose ps
          
      - name: Stop Docker Compose
        if: always()
        run: |
          docker compose down